name: Check and Unit Test

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

env:
  PACKAGE_NAME: zfl-website
  ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
  PUBLIC_STAGE: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}

permissions:
  contents: read

jobs:
  licenses-format-lint-typecheck-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061
        name: Install pnpm

      - name: Cache pnpm dependencies
        id: cache-pnpm-deps
        uses: actions/cache@v5
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache-pnpm-deps.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Audit used licences
        run: pnpm run audit:licences

      - name: Fix formatting issues
        run: pnpm run format:fix

      - name: Lint
        run: pnpm run lint:fix

      - name: Check types
        run: pnpm run typecheck

      - name: Run unit tests
        run: pnpm test

      - name: Send failure to Slack
        uses: digitalservicebund/notify-on-failure-gha@814d0c4b2ad6a3443e89c991f8657b10126510bf # v1.5.0
        if: ${{ failure() }}
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
