name: Check and Test

on:
  workflow_call:

env:
  PACKAGE_NAME: zfl-website
  ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
  PUBLIC_STAGE: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}

permissions:
  contents: read

jobs:
  licenses-format-lint-typecheck-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install -g pnpm && pnpm install

      - name: Audit used licences
        run: pnpm run audit:licences

      - name: Fix formatting issues
        run: pnpm run format:fix

      - name: Lint
        run: pnpm run lint:fix

      - name: Check types
        run: pnpm run typecheck

      - name: Run unit tests
        run: pnpm test
